# https://dev.azure.com/mattorb/dotfiles/

strategy:
  matrix:
    macLatest:
      imageName: 'macos-latest'
    macMojave:
      imageName: 'macos-10.14'
    macSierra:
      imageName: 'macos-10.13'

trigger:
- master

pool:
  vmImage: $(imageName)

steps:
- script: ./setup.sh
  displayName: 'run setup'
  