# https://dev.azure.com/mattorb/dotfiles/

strategy:
  matrix:
    macLatest:
      imageName: 'macOS-latest'
    macCatalina:
      imageName: 'macOS-10.15'

trigger:
- master

pool:
  vmImage: $(imageName)

steps:
- script: ./.cisupport/pre.sh
  displayName: 'Check versions of pre-installed software/system'
- script: ./setup.sh
  displayName: 'run setup'
- script: ./.cisupport/post.sh
  displayName: 'Check installed versions'
  