name: Smoke Test CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Execute full install
      run:  ./setup.sh
    - name: Record installed brew package versions to CI log
      run: brew list --versions
    - name: Record installed Casks to CI log
      run: brew cask list --versions
        
        
